version: '3'
# Relies on components in mcsvc-netfix-infra project

services:

  #Eureka Service
  discovery:
    container_name: mcsvc-eureka-service
    image: mcsvc-infra-eureka-service:latest
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=mcsvc-eureka-service
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    networks:
      - discovery
    restart: on-failure

  #Spring cloud config server
  config:
    container_name: mcsvc-config-service
    image: mcsvc-infra-config-service:latest
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    environment:
      - EUREKA_HOST=mcsvc-eureka-service
      - GIT_URL=${GIT_URL}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_PASSWORD=${GIT_PASSWORD}
    networks:
      - discovery
    restart: on-failure

    #Codecentic Spring Boot Admin
  admin:
    container_name: mcsvc-admin-service
    image: mcsvc-infra-admin-service:latest
    ports:
      - "9000:9000"
    depends_on:
      - discovery
      - config
    environment:
      - EUREKA_HOST=mcsvc-eureka-service
    networks:
      - discovery
    restart: on-failure

  constants-service:
    container_name: mcsvc-util-constants-service
    image: mcsvc-util-constants-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery
      - config
      - admin
    environment:
      - EUREKA_HOST=mcsvc-eureka-service
    networks:
      - discovery
    restart: on-failure


networks:
  discovery:



